name: ceos-lab

topology:
  nodes:
    ceos1:
      kind: ceos
      image: ceos:latest
      mgmt-ipv4: 172.20.20.3

    ceos2:
      kind: ceos
      image: ceos:latest
      mgmt-ipv4: 172.20.20.2

    ceos3:
      kind: ceos
      image: ceos:latest
      mgmt-ipv4: 172.20.20.4

  links:
    - endpoints: ["ceos1:eth1", "ceos2:eth1"]
    - endpoints: ["ceos2:eth2", "ceos3:eth1"]
    - endpoints: ["ceos1:eth2", "ceos3:eth2"]
